// <auto-generated />
using System;
using BarberShop.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberShop.API.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20260520061229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberShop.API.Models.Barbero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Barberos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaIngreso = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Mendoza",
                            PorcentajeComision = 50m,
                            Telefono = "6621234567"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaIngreso = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis Ramírez",
                            PorcentajeComision = 50m,
                            Telefono = "6629876543"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaIngreso = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel Torres",
                            PorcentajeComision = 45m,
                            Telefono = "6625551234"
                        });
                });

            modelBuilder.Entity("BarberShop.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Color = "#3B82F6",
                            Nombre = "Cortes"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Color = "#10B981",
                            Nombre = "Barba"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Color = "#8B5CF6",
                            Nombre = "Combos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Color = "#F59E0B",
                            Nombre = "Extras"
                        });
                });

            modelBuilder.Entity("BarberShop.API.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("BarberShop.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Pomada Calavera",
                            Precio = 120m,
                            Stock = 20,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Cera Mate",
                            Precio = 100m,
                            Stock = 15,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Shampoo Barba",
                            Precio = 150m,
                            Stock = 10,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Aceite para Barba",
                            Precio = 180m,
                            Stock = 8,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Gorra M&A",
                            Precio = 250m,
                            Stock = 12,
                            StockMinimo = 5
                        });
                });

            modelBuilder.Entity("BarberShop.API.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            DuracionMinutos = 30,
                            Nombre = "Corte Clásico",
                            Precio = 80m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            DuracionMinutos = 45,
                            Nombre = "Corte Moderno",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            DuracionMinutos = 20,
                            Nombre = "Corte Infantil",
                            Precio = 60m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 2,
                            DuracionMinutos = 20,
                            Nombre = "Arreglo de Barba",
                            Precio = 60m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 2,
                            DuracionMinutos = 30,
                            Nombre = "Rasurado Clásico",
                            Precio = 80m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 3,
                            DuracionMinutos = 60,
                            Nombre = "Combo Corte + Barba",
                            Precio = 130m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 4,
                            DuracionMinutos = 60,
                            Nombre = "Tinte",
                            Precio = 150m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 4,
                            DuracionMinutos = 15,
                            Nombre = "Cejas",
                            Precio = 40m
                        });
                });

            modelBuilder.Entity("BarberShop.API.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("BarberShop.API.Models.DetalleVenta", b =>
                {
                    b.HasOne("BarberShop.API.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId");

                    b.HasOne("BarberShop.API.Models.Servicio", "Servicio")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ServicioId");

                    b.HasOne("BarberShop.API.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Servicio");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BarberShop.API.Models.Servicio", b =>
                {
                    b.HasOne("BarberShop.API.Models.Categoria", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BarberShop.API.Models.Venta", b =>
                {
                    b.HasOne("BarberShop.API.Models.Barbero", "Barbero")
                        .WithMany("Ventas")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("BarberShop.API.Models.Barbero", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BarberShop.API.Models.Categoria", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("BarberShop.API.Models.Producto", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("BarberShop.API.Models.Servicio", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("BarberShop.API.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
